export const colors = {
  primary: '#14B8C4',
  primaryDark: '#0E8A93',
  primarySoft: '#E0F7F9',
  accent: '#A8E232',
  accentDark: '#7DAB1F',
  accentSoft: '#F0FBD8',
  secondary: '#7C3AED',
  secondaryDark: '#5B21B6',
  secondarySoft: '#EDE5FE',
  success: '#84CC16',
  successDark: '#4D7C0F',
  warning: '#F59E0B',
  error: '#EF4444',
  errorSoft: '#FEE2E2',
  textPrimary: '#0F1B3D',
  textSecondary: '#5B6478',
  textMuted: '#94A0B8',
  background: '#F4F8FB',
  surface: '#FFFFFF',
  surfaceAlt: '#EFF6FB',
  border: '#DDE5EE',
  borderStrong: '#C2CFDC',
  overlay: 'rgba(15,27,61,0.65)',
  onPrimary: '#FFFFFF',
  onAccent: '#0F1B3D',
  onSecondary: '#FFFFFF',
  badgePendingBg: '#FFF1D6',
  badgePendingText: '#B45309',
  badgePaidBg: '#E6F7C8',
  badgePaidText: '#4D7C0F',
  badgeDraftBg: '#E2E8F0',
  badgeDraftText: '#475569',
  badgeActiveBg: '#E0F7F9',
  badgeActiveText: '#0E8A93',
} as const;

export const categoryColors: Record<string, { bg: string; fg: string; soft: string }> = {
  comida: { bg: '#FF8A4C', fg: '#FFFFFF', soft: '#FFE7D6' },
  deporte: { bg: '#14B8C4', fg: '#FFFFFF', soft: '#E0F7F9' },
  fiesta: { bg: '#7C3AED', fg: '#FFFFFF', soft: '#EDE5FE' },
  cultura: { bg: '#0EA5E9', fg: '#FFFFFF', soft: '#E0F2FE' },
  aire_libre: { bg: '#A8E232', fg: '#0F1B3D', soft: '#F0FBD8' },
  otros: { bg: '#94A0B8', fg: '#FFFFFF', soft: '#EAEEF3' },
};

export type ColorKey = keyof typeof colors;
