export const colors = {
  primary: '#FF8775',
  primaryDark: '#C8553D',
  primarySoft: '#FFE5DD',
  primaryMuted: '#F5B5A8',
  accent: '#A8E232',
  accentDark: '#7DAB1F',
  accentSoft: '#F0FBD8',
  secondary: '#7C3AED',
  secondaryDark: '#5B21B6',
  secondarySoft: '#EDE5FE',
  success: '#84CC16',
  successDark: '#4D7C0F',
  warning: '#F59E0B',
  error: '#EF4444',
  errorSoft: '#FEE2E2',
  textPrimary: '#1B2240',
  textSecondary: '#5B6478',
  textMuted: '#94A0B8',
  background: '#FCEFE9',
  surface: '#FFFFFF',
  surfaceAlt: '#FFF6F2',
  border: '#F0DED5',
  borderStrong: '#E1C7BB',
  overlay: 'rgba(27,34,64,0.65)',
  onPrimary: '#FFFFFF',
  onAccent: '#1B2240',
  onSecondary: '#FFFFFF',
  badgePendingBg: '#FFF1D6',
  badgePendingText: '#B45309',
  badgePaidBg: '#E6F7C8',
  badgePaidText: '#4D7C0F',
  badgeDraftBg: '#E7E0DC',
  badgeDraftText: '#5B4A43',
  badgeActiveBg: '#FFE5DD',
  badgeActiveText: '#C8553D',
} as const;

export const categoryColors: Record<string, { bg: string; fg: string; soft: string }> = {
  comida: { bg: '#FF8A4C', fg: '#FFFFFF', soft: '#FFE7D6' },
  deporte: { bg: '#14B8C4', fg: '#FFFFFF', soft: '#E0F7F9' },
  fiesta: { bg: '#7C3AED', fg: '#FFFFFF', soft: '#EDE5FE' },
  cultura: { bg: '#0EA5E9', fg: '#FFFFFF', soft: '#E0F2FE' },
  aire_libre: { bg: '#A8E232', fg: '#0F1B3D', soft: '#F0FBD8' },
  otros: { bg: '#94A0B8', fg: '#FFFFFF', soft: '#EAEEF3' },
};

export type ColorKey = keyof typeof colors;
