export const SLANG = {
  helloUser: (name: string) => `¡Habla, ${name}!`,
  ctaCreatePlan: 'Arma el plan',
  ctaSpinRoulette: '¡Tira la ruleta!',
  ctaShare: 'Pasa la voz',
  ctaMarkPaid: 'Cayó la cuota',
  ctaLogout: 'Chaufa',
  ctaCreateAccount: 'Crear cuenta',
  ctaHaveAccount: 'Ya tengo cuenta',
  ctaEnter: 'Entrar',
  ctaCreateGroup: 'Armar collera',
  ctaCreateEvent: 'Crear evento',
  ctaConfirm: 'De ley',
  ctaSoftCancel: 'Mejor después',
  ctaSpinAgain: 'Otra vuelta',
  ctaUseThisPlan: 'Arma evento con este',
  ctaShareWhatsapp: 'Compartir por WhatsApp',
  ctaCopyMessage: 'Copiar mensaje',
  ctaCopy: 'Copiar al portapapeles',
  ctaMarkPayments: 'Marcar pagos',
  ctaJoinCaepe: 'Únete a CaePe',
  ctaBackHome: 'Volver al inicio',
  ctaSave: 'Guardar',
  ctaConfirmEvent: 'Confirmar evento',
  ctaAddParticipant: '+ Agregar',
  fundedTitle: '¡Cayó! Plan armado',
  fundedSubtitle: 'Todos pagaron, mostro. Disfruten el plan.',
  rouletteResult: '¡Qué paja! Tu planazo:',
  emptyGroups: 'Aún sin collera. Arma una.',
  emptyEvents: 'Sin planes todavía. Arma uno.',
  paymentExternal: 'El pago va por fuera. No te hagas paltas.',
  errorGeneric: 'Palta, intenta de nuevo.',
  loading: 'Al toque...',
  reminderUnpaid: '¡Yara! Aún falta tu cuota.',
  badgePending: 'Falta pagar',
  badgePaid: 'Pagado',
  sectionGroups: 'Tu collera',
  sectionEvents: 'Eventos próximos',
  tagline: 'Arma planes con tu collera. Divide cuentas. Sin mover plata por la app.',
} as const;
